SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "Asteroids Game"


SHIP_ACCELERATION = 0.2
SHIP_ROTATION_SPEED = 3
SHIP_MAX_SPEED = 5
FRICTION = 0.95

BULLET_SPEED = 8
BULLET_LIFETIME = 60

ASTEROID_BASE_SPEED = 1.5
ASTEROID_SCALE = 0.5

DATA_PATH = "data/highscore.txt"
